### PR TITLE
Update toolchain file and CI action

### PR DESCRIPTION
**Pull request by uklotzde**
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
https://github.com/actions-rs/toolchain

### CODE REVIEW

**Comment by flosse** [comment]
Hmm... the CI says `toolchain input was not given and repository does not have a rust-toolchain file` :disappointed:

**Comment by uklotzde** [comment]
Oh, then this seems to be a bug in the action. They claim to support toolchain files and link to the documentation:

https://github.com/actions-rs/toolchain#the-toolchain-file

**Comment by uklotzde** [comment]
Looks like we have to redundantly specify the toolchain config for the action. This could also be the reason for the recent build failures.

**Comment by uklotzde** [comment]
Fixed, though clippy still fails.

**Comment by flosse** [comment]
> Fixed,

:+1:

**Comment by wellemut** [comment]
Thanks @uklotzde 
Great, that you have been part of the Hackathon ;)

**Pull request merged**
