### PR TITLE
Clearance: Permissions for moderated tags & clearance of place revisions by organizations

### PR DESCRIPTION
**Pull request by uklotzde**
Keep track of place edits that need to be authorized by an organization before they appear on the organization's custom map view. This feature basically provides a *TODO list for organizations*. Items from the list need to be handled and could then be deleted when done.

Organizations will be able to define criteria which places need to be authorized depending on hash tags, the region/bounding box, or other properties. This needs to be implemented as a separate task!

### Technical concept

As a reference the last last revision and review status of a place is stored after it has been edited. This could be used to determine and display the differences to the current revision.

Search requests by an organization (TODO: new parameter) should exclude all newer revisions and only return the last authorized revision. This requires filtering and modification of search results based on the contents of the new table `organization_place_unauthorized` as a post-processing step:

- Unauthorized new place: Remove from search results
- Unauthorized updated place, i.e. new revision and/or review status changed
  - Last authorized review status = created/confirmed: Replace with last authorized revision
  - Last authorized review status = archived/rejected: Remove from search results

### Important note
The search will always only operate on the **current revision** of all entries!! This feature will ***not*** provide an isolated, different view of the world for organizations. There is only one reality, deal with it ;)

All records in the new database table are supposed to exist for a short period time until organizations have reviewed, edited, and authorized the pending changes.

### CODE REVIEW

**Comment by wellemut** [comment]
Thanks @uklotzde that looks great.
To summarize the workflow:

1. User edits an entry on mapoftomorrow
-> changes are directly visible on mapoftomorrow (without filter)
-> changes are not visible on the organisational iframe (withe a specific hashtag)
2a. Organisations approves it
-> Version in the organisational iframe is the same as on mapoftomorrow
2b. Organisation dismisses the change
-> The version on mapoftomorrow goes back to the version of the organizational iframe
2c. The organisation does not react at all
-> the old versions stays the same in the iframe. On mapoftomorrow there are allways the newest change visible.

Note:
- The status question can always be linked to an hashtag: No matters if I am in an iframe or directly on kartevonmorgen.org, when I filter for #montessori I only get those entries which are approved by the owner of montessori.

**Comment by uklotzde** [comment]
>        2b. Organisation dismisses the change
>        -> The version on mapoftomorrow goes back to the version of the organizational iframe

Changes cannot be reverted, revisions are immutable. You could only submit a new revision that copies the old revision.

**Comment by uklotzde** [comment]
> Note:
> - The status question can always be linked to an hashtag: No matters if I am in an iframe or directly on kartevonmorgen.org, when I filter for #montessori I only get those entries which are approved by the owner of montessori.

I don't recommend filtering the search results based on *owned tags* in general. Otherwise this would incur a huge performance hit caused by the post-processing of all owned tags. The post-processing should only be applied for a *single* organization for each search and only when explicitly requested. We don't plan to censor results for everyone!

Organizations are responsible for reviewing their authorizations if they want to ensure that the generic results on mapoftomorrow match their expectations. In their own iFrame they can decide to hide unauthorized entries by providing their organization id as an additional parameter.

This strategy ensures that unauthorized entries are reviewed timely and that the case 2c. does not apply.

**Comment by uklotzde** [comment]
API spec: https://github.com/kartevonmorgen/openfairdb/pull/269/commits/442134fbd275d875a49cb389d44ba3c684ca2e79

**Comment by wellemut** [comment]
great!

**Pull request merged**
