### PR TITLE
Clearance center: reduce WASM file size

### PR DESCRIPTION
**Pull request by flosse**
By removing the dependency of `ofdb-entities` the file size can be reduced from 729k to 451k.

The main reason is that `ofdb-entities` depends on `url` that itself has bloated dependencies.
So what do you think, should we replace the `url::Url` in `ofdb-entities` with a custom `struct Url(String)`?

### CODE REVIEW

**Comment by magdaddy** [comment]
Is the file size in this case (clearance center) really important?

I see that no special features of url are used in ofdb-entities, so it could be ok to use a custom struct.

But I wonder... url is also used in ofdb-boundary, so it should be included anyway.
Also, for a web app like clearance-center, the use of urls is central, so I suppose one wants to use it at some point anyway.

So unless there is a good reason for reducing the file size, I would say it's not worth kicking out the url dependency...

**Comment by flosse** [comment]
> Is the file size in this case (clearance center) really important?

no, in this case it's absolutely not relevant, it's just a "playground" to play with ;-)
But creating a more complex OFDB frontend app that is used in a mobile context, the file size is important.
 
> I see that no special features of url are used in ofdb-entities, so it could be ok to use a custom struct.

...and even if a special url feature is required it could be transformed.
 
> But I wonder... url is also used in ofdb-boundary, so it should be included anyway.

nope, not anymore (since `v0.9.5`)

> Also, for a web app like clearance-center, the use of urls is central, so I suppose one wants to use it at some point anyway.

It depends what exactly you're going to do. I guess in most cases you'd use [seeds `Url`](https://docs.rs/seed/0.8.0/seed/browser/url/struct.Url.html) lightweight implementation.
 
> So unless there is a good reason for reducing the file size, I would say it's not worth kicking out the url dependency...

I really think it's an important reason for mobile friendly apps.

**Comment by magdaddy** [comment]
All right then... I have no further objections.

**Comment by flosse** [comment]
This PR is obsolete because `ofdb-entities` does not depend on URL anymore by default.
Moreover `ofdb-entities` should not used in the frontend anyway.

**Pull request closed without merging**
