### PR TITLE
Update rust toolchain

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by uklotzde** [comment]
Didn't notice that clux/muslrust is not (yet?) available for this version. We need it for building the executable and releasing a new version. The nightly toolchain bites us once again.

**Comment by uklotzde** [comment]
https://hub.docker.com/r/clux/muslrust/tags

**Comment by uklotzde** [comment]
In nightly-2019-10-18 clippy is missing.

**Comment by flosse** [comment]
> Didn't notice that clux/muslrust is not (yet?) available for this version. We need it for building the executable and releasing a new version. The nightly toolchain bites us once again.

I'm so sorry, I just looked at https://rust-lang.github.io/rustup-components-history/ for "Tier1" :(

**Comment by flosse** [comment]
So lets revert it: https://github.com/kartevonmorgen/openfairdb/pull/213

**Comment by flosse** [comment]
... or we just make a `push --force` to the master with 113b8738a786edb2b348815175150f21c4644bcc

**Pull request merged**
