### PR TITLE
Add pre-commit hooks with GitHub CI integration

### PR DESCRIPTION
**Pull request by uklotzde**
TODO:
  - [x] Fix all issues before merging
  - [x] Rebase and update after merging #358

https://pre-commit.com/

Install and run locally:
  pip install -U pre-commit
  pre-commit autoupdate
  pre-commit run --all-files

### CODE REVIEW

**Comment by uklotzde** [comment]
```
pre-commit run --all-files
Check for case conflicts.................................................Passed
Check JSON...............................................................Passed
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Toml...............................................................Passed
Check Xml............................................(no files to check)Skipped
Check Yaml...............................................................Passed
Detect Destroyed Symlinks................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
fix UTF-8 byte order marker..............................................Passed
Forbid new submodules....................................................Passed
Mixed line ending........................................................Passed
Don't commit to branch...................................................Passed
Trim Trailing Whitespace.................................................Passed
codespell................................................................Failed
- hook id: codespell
- exit code: 65

openapi.yaml:23: oder ==> order, odor
openapi.yaml:64: similiar ==> similar
openapi.yaml:193: specifid ==> specified
openapi.yaml:343: Dependening ==> Depending
openapi.yaml:502: Sucessfully ==> Successfully
openapi.yaml:522: Sucessfully ==> Successfully
openapi.yaml:563: Sucessful ==> Successful
openapi.yaml:577: Sucessful ==> Successful
openapi.yaml:608: Sucessful ==> Successful
openapi.yaml:629: Sucessful ==> Successful
openapi.yaml:650: Sucessful ==> Successful
openapi.yaml:658: Sucessful ==> Successful
openapi.yaml:672: Sucessful ==> Successful
openapi.yaml:680: Sucessful ==> Successful
openapi.yaml:695: Sucessful ==> Successful
openapi.yaml:742: paramaters ==> parameters
openapi.yaml:789: paramaters ==> parameters
openapi.yaml:1504: Therfore ==> Therefore
src/infrastructure/db/tantivy/mod.rs:397: occurence ==> occurrence
src/ports/web/frontend/view/mod.rs:54: placeholer ==> placeholder
src/ports/web/frontend/tests.rs:556: sucess ==> success
src/core/usecases/find_duplicates.rs:78: otherweise ==> otherwise
search_results.json:123: ist ==> is, it, its, it's, sit, list
search_results.json:159: alle ==> all, alley
search_results.json:214: oder ==> order, odor
search_results.json:284: Ende ==> End
search_results.json:307: Handel ==> Handle
search_results.json:328: nin ==> inn, min, bin, nine
search_results.json:404: Alle ==> All, alley
search_results.json:466: ist ==> is, it, its, it's, sit, list
search_results.json:466: Als ==> Also
search_results.json:493: ist ==> is, it, its, it's, sit, list
search_results.json:615: ist ==> is, it, its, it's, sit, list
search_results.json:615: Adresse ==> Address
search_results.json:615: Accessoires ==> Accessories, accessorise
search_results.json:689: als ==> also
search_results.json:795: alle ==> all, alley
search_results.json:818: ist ==> is, it, its, it's, sit, list
search_results.json:818: als ==> also
search_results.json:835: unter ==> under
search_results.json:893: ist ==> is, it, its, it's, sit, list
search_results.json:893: Alle ==> All, alley
search_results.json:931: ist ==> is, it, its, it's, sit, list
search_results.json:989: ist ==> is, it, its, it's, sit, list
search_results.json:1110: Toleranz ==> Tolerance
search_results.json:1110: sie ==> size, sigh
search_results.json:1130: toleranz ==> tolerance
search_results.json:1142: Plattform ==> Platform
search_results.json:1185: ist ==> is, it, its, it's, sit, list
search_results.json:1264: ist ==> is, it, its, it's, sit, list
search_results.json:1292: ist ==> is, it, its, it's, sit, list
search_results.json:1292: als ==> also
search_results.json:1328: ist ==> is, it, its, it's, sit, list
search_results.json:1475: ist ==> is, it, its, it's, sit, list
search_results.json:1475: Plattform ==> Platform
search_results.json:1475: alle ==> all, alley
search_results.json:1634: alle ==> all, alley
search_results.json:1750: ist ==> is, it, its, it's, sit, list
search_results.json:1867: Als ==> Also
search_results.json:1917: Plattform ==> Platform
search_results.json:1976: alle ==> all, alley
search_results.json:2031: Accessoires ==> Accessories, accessorise
search_results.json:2050: ist ==> is, it, its, it's, sit, list
search_results.json:2050: ist ==> is, it, its, it's, sit, list
search_results.json:2112: accessoires ==> accessories, accessorise
search_results.json:2139: Alle ==> All, alley
src/ports/web/api/tests.rs:1358: TOOD ==> TODO
ofdb-gateways/src/sendmail.rs:144: adresses ==> addresses
ofdb-entities/src/organization.rs:11: compatbility ==> compatibility
README.md:30: aplication ==> application
src/ports/web/frontend/register.rs:52: sucessfully ==> successfully
src/ports/web/frontend/mod.rs:272: achive ==> achieve, archive
src/ports/web/frontend/mod.rs:279: achive ==> achieve, archive
src/ports/web/frontend/mod.rs:354: achive ==> achieve, archive
ofdb-gateways/src/user_communication.rs:14: interaktive ==> interactively
ofdb-gateways/src/user_communication.rs:15: oder ==> order, odor
ofdb-gateways/src/user_communication.rs:48: deine ==> define
ofdb-gateways/src/user_communication.rs:52: deine ==> define
ofdb-gateways/src/user_communication.rs:113: Adresse ==> Address
ofdb-gateways/src/user_communication.rs:117: oder ==> order, odor
ofdb-gateways/src/user_communication.rs:172: Beginn ==> Begin
ofdb-gateways/src/user_communication.rs:173: Ende ==> End
ofdb-gateways/src/user_communication.rs:176: Adresse ==> Address
ofdb-gateways/src/user_communication.rs:180: oder ==> order, odor
src/infrastructure/db/sqlite/util.rs:32: Convertion ==> Conversion
CHANGELOG.md:21: Chache ==> Cache
src/ports/web/frontend/login.rs:88: Sie ==> Size, sigh
ofdb-gateways/src/mailgun.rs:63: adresses ==> addresses

fmt......................................................................Passed
cargo check..............................................................Passed
clippy...................................................................Failed
- hook id: clippy
- exit code: 101

   Compiling openfairdb v0.10.3 (/home/uk/github/kartevonmorgen/openfairdb)
error: used `assert_eq!` with a literal bool
  --> src/core/usecases/confirm_email.rs:38:9
   |
38 |         assert_eq!(db.users.borrow()[0].email_confirmed, true);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
   |
   = note: `-D clippy::bool-assert-comparison` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/core/usecases/create_new_user.rs:149:9
    |
149 |         assert_eq!(db.users.borrow()[0].email_confirmed, false);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/core/usecases/find_duplicates.rs:419:9
    |
419 |         assert_eq!(true, words_equal_except_k_words("ab abc a", "ab abc b", 1));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/core/usecases/find_duplicates.rs:420:9
    |
420 |         assert_eq!(true, words_equal_except_k_words("ab abc a", "abc ab", 1));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/core/usecases/find_duplicates.rs:421:9
    |
421 |         assert_eq!(true, words_equal_except_k_words("ab ac a", "abc ab ab", 2));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/core/usecases/find_duplicates.rs:422:9
    |
422 |         assert_eq!(false, words_equal_except_k_words("a a a", "ab abc", 2));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: redundant field names in struct initialization
   --> src/infrastructure/flows/tests.rs:188:17
    |
188 |                 title: title,
    |                 ^^^^^^^^^^^^ help: replace it with: `title`
    |
    = note: `-D clippy::redundant-field-names` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names

error: used `assert_eq!` with a literal bool
    --> src/ports/web/api/tests.rs:1514:5
     |
1514 | /     assert_eq!(
1515 | |         db.exclusive().unwrap().all_users().unwrap()[0].email_confirmed,
1516 | |         false
1517 | |     );
     | |______^ help: replace it with: `assert!(..)`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
    --> src/ports/web/api/tests.rs:1530:5
     |
1530 | /     assert_eq!(
1531 | |         db.exclusive().unwrap().all_users().unwrap()[0].email_confirmed,
1532 | |         true
1533 | |     );
     | |______^ help: replace it with: `assert!(..)`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/ports/web/frontend/tests.rs:366:9
    |
366 |         assert_eq!(body_str.contains("<form"), false);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/ports/web/frontend/tests.rs:367:9
    |
367 | /         assert_eq!(
368 | |             body_str.contains("action=\"/comments/actions/archive\""),
369 | |             false
370 | |         );
    | |__________^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/ports/web/frontend/tests.rs:382:9
    |
382 |         assert_eq!(body_str.contains("<form"), true);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/ports/web/frontend/tests.rs:383:9
    |
383 | /         assert_eq!(
384 | |             body_str.contains("action=\"/comments/actions/archive\""),
385 | |             true
386 | |         );
    | |__________^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/ports/web/frontend/tests.rs:398:9
    |
398 |         assert_eq!(body_str.contains("<form"), true);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: used `assert_eq!` with a literal bool
   --> src/ports/web/frontend/tests.rs:399:9
    |
399 | /         assert_eq!(
400 | |             body_str.contains("action=\"/comments/actions/archive\""),
401 | |             true
402 | |         );
    | |__________^ help: replace it with: `assert!(..)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison

error: aborting due to 15 previous errors

error: could not compile `openfairdb`
```

**Comment by uklotzde** [comment]
clippy and rustfmt will be run separately from the CI build during *pre-commit*. This fixes at least the *continuous integration* build.

Building and uploading of release builds for all targets (Linux statically linked with musl lib, macOS, Windows) is accomplished by a separate action.

**Comment by flosse** [comment]
musl support for trunk is on the horizon: https://github.com/thedodd/trunk/pull/176

**Comment by uklotzde** [comment]
Ready, waiting for CI.

**Pull request merged**
